import os

SESSION_COOKIE_NAME = 'superset_session'
SECRET_KEY = 'admin'

FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
    "SQL_LAB_BACKEND_PERSISTENCE": True,
}

ENABLE_PROXY_FIX = True

SUPERSET_WEBSERVER_TIMEOUT = 300
SQLLAB_TIMEOUT = 300
